Pond tests
StanfordAHA/lake pull request #72
Opened 2020-10-19 05:42 UTC by ankita0805

- Pond test in write followed by read mode
- Pond test in double buffer mode
- Parameterize read start_addr for write/read test

2020-10-19 05:50 UTC, kavyasreedhar approved these changes
looks good to me

2020-10-20 18:30 UTC, mbstrange2 requested changes
Just refactor to use purest param and I'll approve

2020-10-20 18:30 UTC, mbstrange2 commented on tests/test_pond_rd_wr.py
> +    # Parameterize on start addr for read
Can you use the pytest parameterize to do this?

Here's an example - https://github.com/StanfordAHA/lake/blob/master/tests/test_reg_fifo.py#L12

2020-11-09 18:08 UTC, closed without merging

2020-11-09 18:08 UTC, ankita0805 commented
Obsolete.