Separate accessors
StanfordAHA/lake pull request #91
Opened 2020-11-11 03:55 UTC by mbstrange2

Separate controller paths for each input and output of the memory tile...

2020-11-13 06:47 UTC, kavyasreedhar requested changes

2020-11-13 06:47 UTC, kavyasreedhar commented on lake/utils/test_infra.py
> +        tempdir = "temp_separate"
delete

2020-11-13 06:47 UTC, kavyasreedhar commented on lake/utils/test_infra.py
> +                               flags=["-Wno-fatal", "--trace"])
delete trace

2020-11-13 06:47 UTC, kavyasreedhar commented on tests/test_lake.py
> +@pytest.mark.parametrize("args", [lake_test_app_args("separate")])
Can separate be added as a second value for args so we keep the first test too?

2020-11-13 06:49 UTC, kavyasreedhar approved these changes

2020-11-18 03:54 UTC, mbstrange2 commented
Passes AHA PR https://github.com/StanfordAHA/aha/pull/1025

https://buildkite.com/stanford-aha/aha-flow/builds/4066#288af191-a248-494f-b13f-403adb32693f

2020-11-18 03:54 UTC, merged